### ISSUE TITLE
Add Value_Template - Modify the value with Jinja templating

### ISSUE THREAD

**Issue by GuyKh** [custom-cards/state-attribute-element#16]
**Is your feature request related to a problem? Please describe.**
Using [Authenticated](https://github.com/custom-components/authenticated) for printing out last IP login.
One of the fields I use is date - and I get this:
![image](https://user-images.githubusercontent.com/3136012/79955527-98f70b80-8487-11ea-92e5-54eae7e44a51.png)

**Describe the solution you'd like**
I'd really love to have the option to format the printed value.
e.g. 
```
  - attribute: last_authenticated_time
    entity: sensor.last_successful_authentication
    prefix: '<b style=''font-weigth: bold; color: orange''>At: </b>'
    style:
      left: 5px
      top: 30%
      transform: none
     value_template: "{{ as_timestamp([value]) | timestamp_custom('%D %-I:%M %P') }}"     # <--- new part
    type: 'custom:state-attribute-element'
```

**Describe alternatives you've considered**
The other option I have is to create a template sensor, but that is much less dynamic and less flexible

**Additional context**
